### ISSUE TITLE
GoogleSignInSwift build errors for Archive and SwiftUI Preview

### ISSUE THREAD

**Issue by Joebayld** [google/GoogleSignIn-iOS#153]
I'm having an issue when running a SwiftUI preview on my device while using this library. There's a bunch of errors thrown.. Attaching a screenshot for reference. 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/9399317/170360781-9e4edf77-010f-4218-894a-8152ab624acd.png">

Whats odd is that it works fine when running the app on my device or in the simulator. It's really just an issue with SwiftUI previews on device. Any ideas?

**Comment by Joebayld** [comment]
An update on this: 

I am also able to Archive an app. The same errors are thrown when Archiving an app.

**Comment by mdmathias** [comment]
Hello! I'm not sure what the issue is here. I was able to generate a preview of our sample app on my test device locally like the below.

![image](https://user-images.githubusercontent.com/4029922/170384007-f3c054f1-2537-4a50-bdc7-00ee01488196.png)

Is it perhaps related to not having a preview made for your view? Or, maybe you're haven't added the GoogleSignInSwift dependency or imported it correctly? Another idea: perhaps the version of iOS you're trying to run against is too low? The `GoogleSignInButton` requires iOS 13 or higher.

**Comment by mdmathias** [comment]
Thanks! I can reproduce this and am looking into it.

**Comment by petea** [comment]
Thanks for bringing this to our attention.  There is currently a problem with building the GoogleSignInSwift target for release (Archive, Analyze, and on device Swift Previews apparently) on iOS when using Swift Package Manager (SPM).  This does not impact SPM macOS builds or CocoaPods builds for either iOS or macOS.

Because the Swift package shares platform min versions between its two targets (GoogleSignIn and GoogleSignInSwift), when building for iOS, the GoogleSignInSwift target is unnecessarily built with an armv7 slice and this part of the build fails with missing SwiftUI symbol errors.  We are working on a solution for this.
