### ISSUE TITLE
GTMSessionFetcher min iOS version conflict

### ISSUE THREAD

**Issue by Innocuousjoe** [google/GoogleSignIn-iOS#252]
**Describe the bug**
Looks like `GTMSessionFetcherCore` bumped to a minimum iOS 10.0 today, which means that resolving package graph now breaks.

`The package product 'GTMSessionFetcherCore' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0 (in target 'GoogleSignIn' from project 'GoogleSignIn')`

and

`The package product 'GTMSessionFetcherCore' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0 (in target 'GTMAppAuth' from project 'GTMAppAuth')`

being the errors in question.

**To Reproduce**
1) Have GoogleSignIn-iOS
2) Attempt to resolve package graph on Bitrise

**Expected behavior**
It builds

**Comment by petea** [comment]
With Friday's release of [GTMSessionFetcher 2.2.0](https://github.com/google/gtm-session-fetcher/releases/tag/v2.2.0), we are seeing build failures when using Swift Package Manager (SPM) on Xcode 13 with this new version of GTMSessionFetcher.  The failure is due to the iOS min version mismatch between both GoogleSignIn and GTMAppAuth (iOS 9) and GTMSessionFetcher 2.2.0 (iOS 10).  Unlike CocoaPods, SPM is unable to resolve this conflict by installing an older version of GTMSessionFetcher (2.1.0) with compatible min versions.

Xcode 14 doesn't exhibit this behavior as it does not support building for iOS 9 and thereby sidesteps the issue.

@thomasvl is considering a patch release of GTMSessionFetcher reverting min iOS to 9 in order to address this problem.

In the meantime, a temporary workaround would be adding a GTMSessionFetcher package dependency to your project with an exact version rule of "2.1.0" in order to prevent SPM from pulling in 2.2.0.

**Comment by petea** [comment]
This has now been addressed with the release of [GTMSessionFetcher 2.3.0](https://github.com/google/gtm-session-fetcher/releases/tag/v2.3.0).
