### ISSUE TITLE
Add "pod lib lint --use-libraries" to GitHub actions to validate GoogleSignIn builds as a library

### ISSUE THREAD

**Issue by jmagman** [google/GoogleSignIn-iOS#33]
Currently there's a GitHub Action to test GoogleSignIn builds as a framework.  Add a test to validate it still builds as a library.
https://github.com/google/GoogleSignIn-iOS/blob/5193a5befc1304c67201cc80f7d2818a0f8aadf4/.github/workflows/tests.yml#L22-L23
```yaml
    - name: Lint podspec using local source as library
      run: pod lib lint --verbose --allow-warnings --use-libraries
```

**Comment by paulb777** [comment]
Here's an example that also tests `--use-static-framework` as well as other Apple platforms - https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/core.yml#L68

**Comment by jmagman** [comment]
https://github.com/firebase/firebase-ios-sdk/blob/04ab074265633049d5518866515e3bd7fc0de246/.github/workflows/core.yml#L78-L79
says
```yml
          # Tests are skipped since the Swift tests need modules.
          '--skip-tests --use-libraries'
```
"Tests are skipped since the Swift tests need modules" is the same bug in that repo as https://github.com/google/GoogleSignIn-iOS/issues/32.  I filed this GitHub Action request to validate the modules are generated for libraries when that issue is fixed, which can be done by adding an `@import GoogleSignIn ` in the unit tests or making any of them Swift files.

**Comment by paulb777** [comment]
That's arguably not a bug since it can be argued that the decision to use modules or not should be left to the pod consumer who can specify `use_frameworks! ` or `use_frameworks! :linkage => :static` to generate frameworks and modules if desired. I believe CocoaPods has always documented that Swift clients should use `use_frameworks! ` and it was changed awhile ago so that the `Podfile` created by `pod init` has `use_frameworks!` on.  I realize that I'm treating modules and frameworks as a synonym, and maybe that's an issue, but we haven't heard about it from Firebase clients.

**Comment by jmagman** [comment]
Indeed, Swift clients should use `use_frameworks!`.  I investigated this more in https://github.com/flutter/flutter/issues/25676#issuecomment-532464440.  However there's no reason not to support module maps regardless of the client language.  `DEFINES_MODULE=YES` is the default build setting in a new vanilla Xcode Objective-C or Swift frameworks target.

In any case for the sake of this GitHub Action request, `--use-libraries` is still a good thing to test for Objective-C clients.

**Comment by paulb777** [comment]
Agreed, and also `--use-static-framework` testing should be added since that is the more modern way to choose static linking.
