### ISSUE TITLE
Xcode 15.3 and App Store Connect Issue

### ISSUE THREAD

**Issue by fahedalahmad** [google/GoogleSignIn-iOS#375]
**Xcode version**

15.3

**Google utils SDK version**

4.2.2

**Dependency Manager**

SPM

**Goals**

Archive my application and upload it to the App Store.

**Expected results**

Processing of the application on the Appstore connect without issues.

**Actual results**

![Screenshot 2024-03-07 at 11 21 19 PM](https://github.com/google/GoogleSignIn-iOS/assets/50173241/6199b972-e4c9-4bdd-ab5a-9e9ea1fc00b8)

**Comment by paulb777** [comment]
Looks like a similar issue to https://github.com/firebase/firebase-ios-sdk/issues/12441.  A workaround should be building with Xcode 15.2 or less.

**Comment by Falahmad** [comment]
Hi @paulb777 ,

It is the same issue, Firebase has fixed it. However, GoogleUtils SDK is not.

I was able to upload the build by manually editing the info.plist of the framework.

**Comment by WillBishop** [comment]
@Falahmad What did you have to put in the Info.plist?

**Comment by Falahmad** [comment]
@WillBishop 

From the organizer -> open the archived by finder -> open the content of the app -> frameworks -> framework which has the issue -> info.plist

MinimumOsVersion = 15.0.0

**Comment by mdmathias** [comment]
Hi @fahedalahmad. I don't think this issue is something that GSI can help with. Seems like the problem here is related to two framework (FBSDKLoginKit and GoogleMapsUtils), neither of these are dependencies of GSI. I suggest that you follow up with the maintainers of those projects to resolve this issue.

I'm closing this for now. Please follow up here if there is something actionable for GSI.

**Comment by mdmathias** [comment]
Also, FWIW, looks like there are already issues for this problem:

https://github.com/googlemaps/google-maps-ios-utils/issues/459
https://github.com/facebook/facebook-ios-sdk/issues/2353
