### ISSUE TITLE
`GIDSignIn.sharedInstance.signIn` does not return a callback sometimes

### ISSUE THREAD

**Issue by doctorsaway** [google/GoogleSignIn-iOS#378]
### Describe the bug

The issue is, the `GIDSignIn.sharedInstance.signIn` method does not return a callback _sometimes_. This bug is a very inconsistent to reproduce. But here are the steps:

### To Reproduce
1. Call the `signIn` method in swift code like so:
```
GIDSignIn.sharedInstance.signIn(
    with: configuration,
    presenting: rootViewController,
    hint: nil,
    additionalScopes: ["https://www.googleapis.com/auth/gmail.readonly"]
) { result, error in
    // Inside the closure
}
```
2. Observe that closure (callback) never gets executed sometimes, but the google sign in sheet is dismissed.

Usually, this occurs the first time during an app-run and the second time, it works as expected. As a result, the implementation has been flaky in our application, leading to users having to sign-in twice each time (most of the times, since it occurs randomly, there are times when the first sign in attempt works as expected)

### Expected behavior
The `GIDSignIn.sharedInstance.signIn` method to work properly and execute the callback consistently, even if there is some error.

### Screenshots
N/A

### Environment
- Device: On several iOS devices, was able to reproduce on iPhone 14 pro, iPhone 13 pro max and iPhone XR.
- OS: iOS 17.3.1 (but also on different versions of iOS 17)
- Browser: N/A

### Additional context
Seems like this has already been mentioned here: https://github.com/google/GoogleSignIn-iOS/issues/360 but without much context. I have added enough context, hoping to help debug this better.

**Comment by mdmathias** [comment]
Hi @doctorsaway this isn't reproducible on our end. Please take a look at our [example apps](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples) to see how you might use this functionality. If there is something that is different, or something that you believe we can address, please reply with more exact reproduction steps (for example, providing context on how your call to `-[GIDSignIn signIn...]` is made would be helpful).

**Comment by marchy** [comment]
@mdmathias 
We are experiencing the same thing, except that it is not intermittent has overnight stopped working altogether.
We've had no change to the same code that was working yesterday, but suddenly today there is no callback firing anymore.

Neither the success nor Cancel scenarios fire the callback anymore.

NOTE: We tried both async and callback APIs and neither are continuing past the initial invocation.

**Invocation code:**
``` Swift
func initiateGoogleAuth_async() async throws -> User {
	do {
		let result:GIDSignInResult = try await GIDSignIn.sharedInstance.signIn( withPresenting: self )
				
		// authenticate
		let user:User = try await self.accountService.authenticate( googleUser: result.user ) //  <--- never gets here

	} catch let error {
		print( "ERROR: \(error)" ) // <--- never gets here
		...
	}
}		


func initiateGoogleAuth_callback( onSuccess:@escaping(User) -> (), onError:@escaping(any Error) -> () ){
	GIDSignIn.sharedInstance.signIn( withPresenting: self ){ (result:GIDSignInResult?, error:(any Error)?) in
		guard let result else {
			print( "ERROR: \(error)" ) // <--- never gets here
			...
			return
		}

		// authenticate
		let user:User = try await self.accountService.authenticate( googleUser: result.user ) //  <--- never gets here
	}
}
```

Could this have anything to do with some security/configuration for the project not being correctly set?

**Comment by marchy** [comment]
**UPDATE:** The callbacks started working again after over an hour of observed downtime.

This is quite concerning as it seems there might be Google back-end issues that the library is not handling. If there are errors they should be surfaced up through the error callback not swallowed and app left in an undetermined state (ie: neither succeeded or failed)

**ASK:** Could the team investigate if any back-end issues were experienced on Apr 11, 2014 prior to 3:30pm UTC (time of my prior post). By 5pm UTC the callbacks started resuming again.

Please keep us posted on this as it is a total blocker to user sign-up / acquisition if this happens intermittently, and we'd like to understand how pervasive this is (ie: % of [SLA](https://cloud.google.com/identity-platform/sla) to expect)

**Comment by marchy** [comment]
Chased this further down and it seems that within `GIDSignIn::addCompletionCallback(..)` (line 859) the `self->_currentOptions.completion` line fails the nil check (in fact `_currentOptions` itself if nil), so it somehow loses reference to the callback passed into the initial SDK by the time the full auth sequence finishes.

<img width="1188" alt="GIDSignIn-CallbackBug 1" src="https://github.com/google/GoogleSignIn-iOS/assets/1369360/5cc40622-7d6e-4be6-abd6-e9fbed7fcee5">


I've confirmed there are no underlying errors and the actual user object is successfully fetched as can be seen in the screenshot above.

Happy to schedule a call and walk the team through any debugging needed to reproduce this on your guys end.

**Comment by mdmathias** [comment]
Hi @marchy. Thanks for the posts and your analysis. Sorry that you're having trouble.

First, let me confirm that I understand your issue. From what I gather, it seems like you're experiencing a kind of race condition due to simultaneous calls to `restorePreviousSignIn()` and `signIn()`, where the restore call is setting `_currentOptions` to nil prior to the sign in call's use of `_currentOptions.completion` to add the completion callback. Therefore, the sign in flow in your app will occasionally not issue a callback due to this race condition. Seems like [this line](https://github.com/google/GoogleSignIn-iOS/blob/main/GoogleSignIn/Sources/GIDSignIn.m#L859) would not pass in this scenario, which would lead to no callback. Is that right?

If my understanding is correct, then it is unfortunately an error to simultaneously call `signIn()` and `restorePreviousSignIn()`. From the library's point of view, it doesn't make sense to restore and sign in at the same time.

Even if we made changes to GSI to protect against this error [1], apps would still have to implement some logic to choose which response to handle. For example, which response is the truth? The sign in or the restore? The completions will not have the same information. 

The practical solution on your end is to make sure that you are signing in and restoring at different points in your app's lifecycle. Ultimately, it's up to apps to manage this. You can take a look at our [Swift sample](https://github.com/google/GoogleSignIn-iOS/blob/main/Samples/Swift/DaysUntilBirthday/Shared/DaysUntilBirthday.swift#L28) and [ObjC sample](https://github.com/google/GoogleSignIn-iOS/blob/main/Samples/ObjC/SignInSample/Source/AppDelegate.m#L28) for inspiration.

[1] I haven't fully thought through the feasibility of your request, but I believe it may require significant refactoring of the library. We'd have to (potentially re-) consider `GIDSignIn`'s singleton status, manage multiple async callback queues on behalf of clients wishing to issue simultaneous and duplicative requests, etc. While I can see ways that this would be useful to callers like yourself (given the scenario you outline above), I have to admit that this sort of change is not feasible at the moment. Of course, since the repo is open source, if you believe you have a simple fix to resolve this, then please send us a PR and we would love to review it!

**Comment by Ariandr** [comment]
Hi @mdmathias 
I have the same issue and I didn't simultaneously call signIn() and restorePreviousSignIn(). I call signIn() only after restorePreviousSignIn() doesn't succeed, not in parallel, but the callback from signIn() is never called. I use v. 8.0

**Comment by Ariandr** [comment]
If anyone needs a workaround for this issue for v.8.0 SDK, you can use this. Works like a charm for me.
It essentially monitors Google Auth controller disappearing. You don't get the error, but you can get the fact that it was presented and dismissed and check the `currentUser` after the dismissal is complete.

Also, you can make the `completion` be called only only once by putting it into a separate optional property and making it `nil` after the first call. But for my use case it's not needed.

```
    private weak var presentingController: UIViewController?
    private var dismissalTimer: Timer?
    private var googleAuthWasPresented = false
    
    private func signInAndRequestCalendarPermission(presenting: UIViewController, completion: @escaping (GIDGoogleUser?, Error?) -> Void) {
        let scopes = [kGTLRAuthScopeCalendar]
        
        // It's a workaround, because signIn() doesn't return a callback in most cases
        self.presentingController = presenting
        startMonitoringDismissal(completion: completion)
        
        GIDSignIn.sharedInstance.signIn(withPresenting: presenting,
                                        hint: nil,
                                        additionalScopes: scopes) { result, error in
            completion(result?.user, error)
        }
    }
    
    private func startMonitoringDismissal(completion: @escaping (GIDGoogleUser?, Error?) -> Void) {
        dismissalTimer?.invalidate()
        dismissalTimer = Timer.scheduledTimer(withTimeInterval: 0.1,
                                              repeats: true) { [weak self] _ in
            guard let self = self else { return }
            
            if self.presentingController?.presentedViewController != nil {
                self.googleAuthWasPresented = true
            } else if self.googleAuthWasPresented {
                print("Presented view controller has been dismissed.")
                completion(GIDSignIn.sharedInstance.currentUser, nil)
                
                self.googleAuthWasPresented = false
                self.presentingController = nil
                self.dismissalTimer?.invalidate()
                self.dismissalTimer = nil
            }
        }
    }
```
