### ISSUE TITLE
[Incompatibility report] GoogleSignIn's latest version depends on GoogleUtilities/UserDefaults ~> 8.0 while GoogleMLKit/TextRecognition for iOS requires GoogleUtilities/UserDefaults < 8.0

### ISSUE THREAD

**Issue by vlvs** [google/GoogleSignIn-iOS#469]
**Describe the bug**
It's impossible to have the current latest versions of `GoogleSignIn` (v8.0.0) and the current latest version of the `GoogleMLKit/TextRecognition` SDK for iOS (v6.0.0) on the same project/target, because:
- `GoogleSignIn` depends on `GoogleUtilities/UserDefaults` ~> 8.0.
- `GoogleMLKit/TextRecognition` depends on `GoogleUtilities/UserDefaults` < 8.0.

**To Reproduce**
Attempt to integrate both SDKs on their latest versions to the same targets of an iOS project.
```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In Podfile:
    GoogleMLKit/TextRecognition (= 6.0.0) was resolved to 6.0.0, which depends on
      GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
        MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleUtilities/UserDefaults (< 8.0, >= 7.13.0)

    GoogleSignIn (= 8.0.0) was resolved to 8.0.0, which depends on
      AppCheckCore (~> 11.0) was resolved to 11.0.0, which depends on
        GoogleUtilities/UserDefaults (~> 8.0)
```

**Expected behavior**
The latest versions of both Google SDKs should be compatible with each other.

**Comment by mdmathias** [comment]
Version 8+ of GoogleUtilities is required because it bumps the minimum iOS support to 12. [iOS 12 is the lowest version of iOS supported by Xcode 15](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15-release-notes), which [is itself required for app store submission](https://developer.apple.com/news/upcoming-requirements/?id=04292024a#:~:text=Apps%20uploaded%20to%20App%20Store,10%20starting%20April%2029%2C%202024.). GoogleMLKit needs to update their dependency accordingly. I suggest you reach out and report an issue on that project if you haven't already.
