### ISSUE TITLE
Open the authentication flow in the default browser, not Safari

### ISSUE THREAD

**Issue by vojtabohm** [google/GoogleSignIn-iOS#480]
**Is your feature request related to a problem you're having? Please describe.**
The current authentication process defaults to opening Safari, even though many users prefer browsers like Arc, Chrome, or Firefox. When Safari isn't their primary browser, users are not signed in and must manually enter their Google credentials.

**Describe the solution you'd like**
Allowing the authentication process to open the user's default browser instead of forcing Safari would streamline the experience. Most users would already be signed in, making Google Sign-In a quick, two-click process.

**Comment by brnnmrls** [comment]
Hi! Thanks for your suggestion. Unfortunately, since our service specifically works with ASWebAuthenticationSession so this is likely not something we can introduce. Google sign-in iOS initiates the sign in flow using ASWebAuthenticationSession, where due to its design and integration with iOS, opens the authentication process in Safari and relies on it. In the case of iOS, the browser opens as a web view versus the default browser ([ref](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)). Closing this since we don't intend to incorporate this, but feel free to open and comment any concerns.

**Comment by vojtabohm** [comment]
I just found this in the docs:

> In macOS, the system opens the user’s default browser if it supports web authentication sessions, or Safari otherwise.

Which means the problem is with the Arc browser. When the default browser is Chrome for example, the `ASWebAuthenticationSession` opens it correctly instead of Safari.

So this is an issue with the Arc browser and not this library, for which I apologise. I will contact Arc and let them know of this.

**Comment by brnnmrls** [comment]
Awesome, hope they can help!
