### ISSUE TITLE
GIDTimedLoader Fails to Release Properly, Causing presentingViewController Memory Leak

### ISSUE THREAD

**Issue by jojochen0620** [google/GoogleSignIn-iOS#495]
**Describe the bug**
When integrating the Google Sign-In SDK and calling the signIn(withPresenting:) method, we observed that the internal GIDTimedLoader class in GIDSignIn can cause presentingViewController to not be released properly. After successful sign-in and authorization, GIDTimedLoader remains retained and continues to hold a reference to presentingViewController, resulting in a memory leak. Where _timedLoader is a private variable that developers cannot directly access or clear.

**To Reproduce**
1.	Integrate Google Sign-In in a Swift project and trigger Google sign-in using the signIn(withPresenting:) method.
2.	Complete sign-in and return to the app.
3.	Attempt to release presentingViewController (e.g., by navigating back to the previous view controller).
4.	Use memory tools (such as Xcode’s memory graph) to observe that presentingViewController is still retained by GIDTimedLoader, causing a memory leak.

**Expected behavior**
After completing the authorization, GIDTimedLoader should be released properly to ensure it no longer retains presentingViewController, thereby avoiding memory leaks.

**Environment**
- Device: [ iPhone 15 Pro ]
- OS: [ iOS 17 ]

**Comment by brnnmrls** [comment]
Hi, thanks for taking the time to investigate and report this potential memory leak. Unfortunately, addressing this might not be on your immediate roadmap. While we can't promise a fix in the very near future, we'd still love to have your contribution. Since the repo is open source, if you believe you have a simple fix to resolve this, then feel free to send us a PR (and tag this issue) and we would love to review it!
