### ISSUE TITLE
I can get GIDSignInResult in debug environment, but can't get it in release  environment with same config

### ISSUE THREAD

**Issue by daizim** [google/GoogleSignIn-iOS#500]
[GIDSignIn.sharedInstance signInWithPresentingViewController:self
                                                      completion:^(GIDSignInResult * _Nullable signInResult, NSError * _Nullable error) {
}];

no error, signInResult in release is 0x0

**Comment by brnnmrls** [comment]
Hi, seeing that it works in your debug environment strongly points to a difference in your project setup or environment. I strongly suggest looking at the differences between your debug and release setup, such as mismatched Client IDs, missing API restrictions, ensuring your `Info.plist` is set up fine, code signing issues, etc.

Closing this since there's likely no action to take on our end but feel free to reopen if issue persists after checking your environments.
